### ISSUE TITLE
Isn't it for sending bulk no. of messages in whatsapp?

### ISSUE THREAD

**Issue by alwinsajip** [hunainahmedj/Whatsapp-bulk-sender#2]
when i hit the send button, nothing happens.

**Comment by alwinsajip** [comment]
I also have a doubt that isn't it free

**Comment by hunainahmedj** [comment]
Yes because you need to create an account on twilio and Wessenger and modify the credentials and key in the app accordingly. Both mentioned services are not free but can be used for trail purposes.

**Comment by alwinsajip** [comment]
how to create account on wessenger

**Comment by hunainahmedj** [comment]
You need to sign up here. https://www.wassenger.com/

**Comment by alwinsajip** [comment]
How long is the trail period

**Comment by alwinsajip** [comment]
Ok. Is this trail valid for 7days only

**Comment by hunainahmedj** [comment]
You can find all the information on their page.
